# Generated by Django 5.2.8 on 2025-11-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libros", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="libro",
            name="categoria",
            field=models.CharField(default="Sin categoria", max_length=100),
        ),
    ]
